### PR TITLE
Fix de/serialization of Invitation roles

### LINKED ISSUE #378: Org invitation call: invalid request with roles
### Describe the problem you'd like to have solved

When attempting invitations to users for an org with 

organizations().createInvitation(orgId, invitation)

the call is failing if we add roles to invitation object as below
```
    List<String> roles = Arrays.asList("some role");
    invitation.setRoles(new Roles(roles));
 ```   
  exception snippet
  
 ```
com.auth0.exception.APIException: Request failed with status code 400: Payload validation error: 'Expected type array but found type object' on property roles (List of roles IDs to associated with the user).
	at com.auth0.net.ExtendedBaseRequest.createResponseException(ExtendedBaseRequest.java:131) ~[auth0-1.34.0.jar:1.34.0]
	at com.auth0.net.ExtendedBaseRequest.parseResponse(ExtendedBaseRequest.java:66) ~[auth0-1.34.0.jar:1.34.0]
	at com.auth0.net.BaseRequest.execute(BaseRequest.java:35) ~[auth0-1.34.0.jar:1.34.0]
```
	
It seems SDK is expecting Roles object [here](https://github.com/auth0/auth0-java/blob/9089a22458e5424e14c8052f6b448215984dacf7/src/main/java/com/auth0/json/mgmt/organizations/Invitation.java#L47) which inturn has List<roles> so the resulting json is turning out to be something like:
```
{
  "inviter" : {
    "name" : "xxxx"
  },
  "invitee" : {
    "email" : "xx@ss.com"
  },
  "client_id" : "<<client-id>>",
  "connection_id" : "<<con-id>>",
  "send_invitation_email" : true,
  "roles" : {
    "roles" : [ "rol_7NdVtrUWWwpcYZz8", "rol_7NdVtrUWWwpcYZz8" ]
  }
}
```

whereas organization invites post request https://auth0.com/docs/api/management/v2#!/Organizations/post_invitations is expecting roles to be a list

```
{
  "inviter": {
    "name": "Jane Doe"
  },
  "invitee": {
    "email": "john.doe@gmail.com"
  },
  "client_id": "AaiyAPdpYdesoKnqjj8HJqRn4T5titww",
  "connection_id": "con_0000000000000001",
  "app_metadata": {},
  "user_metadata": {},
  "ttl_sec": 0,
  "roles": [
    "rol_0000000000000001",
    "rol_0000000000000002"
  ],
  "send_invitation_email": true
}
```
Here is a snippet of how I am using SDK

```
    Inviter inviter = new Inviter(inviterAddress);
    Invitee invitee = new Invitee(userEmail);
    Invitation invitation = new Invitation(inviter, invitee, appClientId);
    invitation.setSendInvitationEmail(true);
    List<String> roles = Arrays.asList(roleId);
    Roles roles = new Roles(rolesList);
    invitation.setRoles(roles);
    invitation.setConnectionId(getConnectionId());
    return executeWithRetry(tokenManager.getMgmt().organizations()
        .createInvitation(orgId, invitation)).getId();
```
### Describe the ideal solution

invitation.setRoles should accept List of Roles to be consistent with request pattern

## Alternatives and current work-arounds

Please suggest if there are any alternatives or correct me if I am not invoking SDK properly

### PR DESCRIPTION
**Pull request by lbalmaceda**
### Changes

The Invitation object has an array of strings for the `roles` ids. This is NOT an object and thus, should not be serialized wrapped as an object.

### References

Fixes #378 without introducing breaking changes.

### Testing

Manually tested with the following snippets. Also, fixed unit tests.

```java
static void assignRole(ManagementAPI api) {
    try {
        api.organizations().addRoles(ORG_ID,
            USER_ID,
            new Roles(Arrays.asList(ADMIN_ROLE_ID)))
            .execute();
    } catch (Auth0Exception e) {
        e.printStackTrace();
    }
}

static void listInvitations(ManagementAPI api) {
    try {
        // Originally failed when invitation contains one or more Roles
        InvitationsPage page = api.organizations().getInvitations(ORG_ID, null).execute();
        for (Invitation i : page.getItems()) {
            System.out.println(i);
        }
    } catch (Auth0Exception e) {
        e.printStackTrace();
    }
}

static void sendInvitation(ManagementAPI api) {
    Invitation invitation = new Invitation(
        new Inviter("Luciano"),
        new Invitee("luciano.balmaceda@auth0.com"),
        CLIENT_ID
    );
    invitation.setRoles(new Roles(Arrays.asList(ADMIN_ROLE_ID)));
    Invitation result;
    try {
        // Originally failed because invitation contains one or more Roles
        result = api.organizations().createInvitation(ORG_ID, invitation).execute();
        System.out.println(result.getInvitationUrl());
    } catch (Auth0Exception e) {
        e.printStackTrace();
    }
}
```

### CODE REVIEW

File: src/main/java/com/auth0/json/mgmt/organizations/Invitation.java [hunk 1]
```diff
@@ -44,14 +51,16 @@
     @JsonProperty("organization_id")
     private String organizationId;
     @JsonProperty("roles")
-    private Roles roles;
+    @JsonDeserialize(using = StringArrayDeserializer.class)
+    @JsonSerialize(using = StringArraySerializer.class)
+    private String[] roles;
```
Comment (jimmyjames) [inline src/main/java/com/auth0/json/mgmt/organizations/Invitation.java:56]: Instead of using a `String[]`, can't we just use a `List<String>`, and keep the `@JsonIgnore` on the getter/setter?

**Review by jimmyjames — CHANGES_REQUESTED** [review]

File: src/main/java/com/auth0/json/mgmt/organizations/Invitation.java (hunk 1 above)
Comment (lbalmaceda) [reply src/main/java/com/auth0/json/mgmt/organizations/Invitation.java]: That actually works, thanks! I fixed that in https://github.com/auth0/auth0-java/pull/380/commits/d682b2f2a1ff615a69f3001aabdb057cf8ddd7f9
