### PR TITLE
[SDK-2975] Fix withOrganization method visibility on token verifier

### LINKED ISSUE #387: doc issue - TokenVerififier withOrganization method
Hi, 
Regarding [https://github.com/auth0/auth0-java/blob/master/README.md#organizations](Organizations),

```
IdTokenVerifier.init("{ISSUER}", "{AUDIENCE}", signatureVerifier)
    .withOrganization("{ORG_ID}")
```

its specified to use .withOrganization method but its package private, its not accessible,
I also searched for usages for this method in the code but didn't found any, is that still needed?

Im using version 1.5.0

### PR DESCRIPTION
**Pull request by jimmyjames**
Fixes #387 by exposing the `withOrganization` builder method on the `IdTokenVerifier`.

### CODE REVIEW

File: src/main/java/com/auth0/utils/tokens/IdTokenVerifier.java [hunk 1]
```diff
@@ -255,26 +255,26 @@ public Builder withLeeway(Integer leeway) {
         }
 
         /**
```
Comment (jimmyjames) [inline src/main/java/com/auth0/utils/tokens/IdTokenVerifier.java:257]: I moved the `withOrganization` method closer to the other public builder methods for readability/organization purposes. The `withClock` method is not removed, the only functional change is making the `withOrganization` method `public`.

**Review by stevehobbsdev — APPROVED** [review]
